CREATE TABLE `podcast_episodes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`guestName` varchar(255) NOT NULL,
	`guestRole` varchar(255),
	`guestCompany` varchar(255),
	`whyNow` text,
	`backgroundUrls` text,
	`backgroundText` text,
	`episodeLengthMin` int DEFAULT 45,
	`showName` varchar(255) DEFAULT 'The Urban Monk Podcast',
	`showDescription` text,
	`audienceDescription` text,
	`reportMarkdown` longtext,
	`sectionDossier` longtext,
	`sectionBigPain` text,
	`sectionThroughLine` text,
	`sectionOutline` longtext,
	`sectionQuestionBank` longtext,
	`sectionSoundbites` text,
	`podcastEpisodeStatus` enum('pending','generating','complete','failed') NOT NULL DEFAULT 'pending',
	`errorMessage` text,
	`episodeNumber` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `podcast_episodes_id` PRIMARY KEY(`id`)
);
