CREATE TABLE `hosted_landing_pages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`hlp_campaign` enum('lo','gut','sleep') NOT NULL DEFAULT 'lo',
	`hlp_slug` varchar(128) NOT NULL,
	`hlp_template` enum('optin','vsl','sales') NOT NULL DEFAULT 'optin',
	`hlp_status` enum('draft','published','archived') NOT NULL DEFAULT 'draft',
	`hlp_title` varchar(255) NOT NULL,
	`hlp_internal_label` varchar(255),
	`hlp_headline` text,
	`hlp_subheadline` text,
	`hlp_hero_image_url` text,
	`hlp_hero_image_key` text,
	`hlp_video_embed_code` text,
	`hlp_video_thumbnail_url` text,
	`hlp_body_copy` longtext,
	`hlp_optin_headline` varchar(255),
	`hlp_optin_button_text` varchar(128) DEFAULT 'Yes, Send It To Me!',
	`hlp_optin_lead_magnet` varchar(255),
	`hlp_kajabi_form_url` text,
	`hlp_thank_you_url` text,
	`hlp_cta_text` varchar(255),
	`hlp_cta_url` text,
	`hlp_cta_subtext` varchar(255),
	`hlp_testimonials` longtext,
	`hlp_fb_pixel_id` varchar(64) DEFAULT '1498608757116877',
	`hlp_ga4_id` varchar(32),
	`hlp_custom_head_scripts` text,
	`hlp_accent_color` varchar(16),
	`hlp_logo_url` text,
	`hlp_view_count` int NOT NULL DEFAULT 0,
	`hlp_optin_count` int NOT NULL DEFAULT 0,
	`hlp_persona_id` int,
	`hlp_ebook_id` int,
	`hlp_webinar_session_id` int,
	`hlp_published_at` timestamp,
	`hlp_created_at` timestamp NOT NULL DEFAULT (now()),
	`hlp_updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `hosted_landing_pages_id` PRIMARY KEY(`id`)
);
