CREATE TABLE `blog_to_youtube_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`wpPostId` int,
	`blogTitle` varchar(512) NOT NULL,
	`blogUrl` varchar(1024) NOT NULL,
	`blogExcerpt` text,
	`blogCategories` text,
	`script` longtext,
	`scriptWordCount` int,
	`scriptGeneratedAt` timestamp,
	`videoTitle` varchar(255),
	`ytDescription` longtext,
	`thumbnailTextOptions` text,
	`vaInstructions` longtext,
	`blogToYoutubeStatus` enum('backlog','scripted','recorded','uploaded','live') NOT NULL DEFAULT 'backlog',
	`productionNotes` text,
	`recordedAt` timestamp,
	`youtubeVideoId` varchar(64),
	`youtubeUrl` varchar(512),
	`uploadedAt` timestamp,
	`descriptionUpdatedAt` timestamp,
	`blogUpdatedWithVideoAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blog_to_youtube_items_id` PRIMARY KEY(`id`)
);
