CREATE TABLE `video_jobs` (
	`vj_id` int AUTO_INCREMENT NOT NULL,
	`vj_content_item_id` int NOT NULL,
	`vj_script_title` varchar(512) NOT NULL,
	`vj_script_text` text NOT NULL,
	`vj_broll_prompt` text,
	`vj_descript_project_id` varchar(256),
	`vj_descript_project_url` text,
	`vj_descript_drive_id` varchar(256),
	`vj_descript_job_id` varchar(256),
	`vj_render_job_id` varchar(256),
	`vj_video_download_url` text,
	`vj_video_s3_key` text,
	`vj_video_s3_url` text,
	`vj_youtube_thumbnail_url` text,
	`vj_youtube_title` varchar(100),
	`vj_youtube_description` text,
	`vj_youtube_tags` text,
	`vj_youtube_video_id` varchar(64),
	`vj_youtube_video_url` text,
	`video_job_status` enum('queued','importing','processing','rendering','ready_for_review','approved','publishing','published','failed','skipped') NOT NULL DEFAULT 'queued',
	`vj_error_message` text,
	`vj_retry_count` int DEFAULT 0,
	`vj_va_approved_at` bigint,
	`vj_published_at` bigint,
	`vj_created_at` timestamp NOT NULL DEFAULT (now()),
	`vj_updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `video_jobs_vj_id` PRIMARY KEY(`vj_id`)
);
