/**
 * Seed script: inserts Pedram Shojai's full media catalog into the media_assets table.
 * Run with: node server/seedMediaAssets.mjs
 */
import { createConnection } from "mysql2/promise";
import * as dotenv from "dotenv";
dotenv.config();

const DB_URL = process.env.DATABASE_URL;
if (!DB_URL) throw new Error("DATABASE_URL not set");

const url = new URL(DB_URL);
const conn = await createConnection({
  host: url.hostname,
  port: Number(url.port) || 3306,
  user: url.username,
  password: url.password,
  database: url.pathname.slice(1),
  ssl: { rejectUnauthorized: false },
});

// ── Media Asset Catalog ────────────────────────────────────────────────────────
const assets = [
  // ── BOOKS ──────────────────────────────────────────────────────────────────
  {
    mediaType: "book",
    title: "The Urban Monk",
    description: "A New York Times bestselling guide to finding peace and purpose in the chaos of modern life, blending Taoist wisdom with practical daily practices.",
    url: "https://www.amazon.com/Urban-Monk-Eastern-Wisdom-Modern/dp/1623366429",
    platform: "Rodale Books",
    publishedYear: 2016,
    topicTags: JSON.stringify(["meditation", "stress", "habits", "time management", "mindfulness", "Taoist wisdom"]),
    credibilitySignal: "New York Times Bestseller",
    reachEstimate: 500000,
    injectionPriority: 1,
    activeInjection: true,
  },
  {
    mediaType: "book",
    title: "The Art of Stopping Time",
    description: "A practical guide to reclaiming your life from the tyranny of busyness — using ancient Taoist time-management practices to create space, presence, and meaning.",
    url: "https://www.amazon.com/Art-Stopping-Time-Practical-Mindfulness/dp/1623369592",
    platform: "Rodale Books",
    publishedYear: 2017,
    topicTags: JSON.stringify(["time management", "mindfulness", "stress", "habits", "presence", "Taoist wisdom"]),
    credibilitySignal: "National Bestseller",
    reachEstimate: 200000,
    injectionPriority: 1,
    activeInjection: true,
  },
  {
    mediaType: "book",
    title: "FOCUS",
    description: "A science-backed guide to reclaiming your attention in the age of distraction — combining neuroscience, Eastern philosophy, and practical protocols for deep focus.",
    url: "https://www.amazon.com/Focus-Bringing-Time-Energy-Money/dp/1401952437",
    platform: "Hay House",
    publishedYear: 2019,
    topicTags: JSON.stringify(["focus", "attention", "productivity", "neuroscience", "habits", "stress"]),
    credibilitySignal: "Hay House Bestseller",
    reachEstimate: 150000,
    injectionPriority: 1,
    activeInjection: true,
  },
  {
    mediaType: "book",
    title: "Exhausted",
    description: "A functional medicine approach to chronic fatigue — identifying the root causes of energy depletion (gut health, cortisol, toxicity) and a step-by-step recovery protocol.",
    url: "https://www.amazon.com/Exhausted-Physicians-Fatigue-Burnout-Reclaim/dp/1401961789",
    platform: "Hay House",
    publishedYear: 2021,
    topicTags: JSON.stringify(["energy", "fatigue", "burnout", "gut health", "cortisol", "functional medicine", "stress"]),
    credibilitySignal: "Hay House",
    reachEstimate: 100000,
    injectionPriority: 2,
    activeInjection: true,
  },
  {
    mediaType: "book",
    title: "Prosperity",
    description: "A holistic guide to building true abundance — redefining wealth through the lens of health, relationships, purpose, and financial freedom using ancient wisdom and modern strategy.",
    url: "https://www.amazon.com/Prosperity-Creating-Abundance-Happiness-Success/dp/1401961797",
    platform: "Hay House",
    publishedYear: 2022,
    topicTags: JSON.stringify(["prosperity", "abundance", "mindset", "purpose", "financial wellness", "Taoist wisdom"]),
    credibilitySignal: "Hay House",
    reachEstimate: 80000,
    injectionPriority: 2,
    activeInjection: true,
  },
  {
    mediaType: "book",
    title: "Grow a Pair",
    description: "A no-nonsense guide to reclaiming personal power, setting boundaries, and building the courage to live authentically — written for men and women ready to stop playing small.",
    url: "https://theurbanmonk.com",
    platform: "Self-Published",
    publishedYear: 2023,
    topicTags: JSON.stringify(["mindset", "courage", "personal power", "boundaries", "authenticity"]),
    credibilitySignal: "Urban Monk Productions",
    reachEstimate: 50000,
    injectionPriority: 3,
    activeInjection: true,
  },
  {
    mediaType: "book",
    title: "Interconnected",
    description: "An exploration of the invisible threads connecting human health, the environment, and global systems — companion book to the documentary film of the same name.",
    url: "https://theurbanmonk.com",
    platform: "Urban Monk Productions",
    publishedYear: 2018,
    topicTags: JSON.stringify(["gut health", "environment", "holistic health", "systems thinking", "microbiome"]),
    credibilitySignal: "Documentary Companion Book",
    reachEstimate: 60000,
    injectionPriority: 3,
    activeInjection: true,
  },
  {
    mediaType: "book",
    title: "Homesick",
    description: "A deep dive into why modern humans feel disconnected from nature, community, and themselves — and how to return to a life of meaning, belonging, and vitality.",
    url: "https://theurbanmonk.com",
    platform: "Urban Monk Productions",
    publishedYear: 2024,
    topicTags: JSON.stringify(["connection", "nature", "community", "mental health", "purpose", "belonging"]),
    credibilitySignal: "Urban Monk Productions",
    reachEstimate: 40000,
    injectionPriority: 3,
    activeInjection: true,
  },

  // ── DOCUMENTARY FILMS ──────────────────────────────────────────────────────
  {
    mediaType: "film",
    title: "Vitality",
    description: "A documentary film exploring the science of longevity, energy, and peak performance — featuring leading experts in functional medicine, nutrition, and ancient healing traditions.",
    url: "https://theurbanmonk.com/vitality",
    platform: "Urban Monk Productions",
    publishedYear: 2014,
    topicTags: JSON.stringify(["energy", "longevity", "functional medicine", "nutrition", "vitality", "peak performance"]),
    credibilitySignal: "Award-Winning Documentary",
    reachEstimate: 500000,
    injectionPriority: 2,
    activeInjection: true,
  },
  {
    mediaType: "film",
    title: "Origins",
    description: "A documentary investigating the root causes of the modern health crisis — tracing the origins of chronic disease to environmental toxins, food systems, and disconnection from nature.",
    url: "https://theurbanmonk.com/origins",
    platform: "Urban Monk Productions",
    publishedYear: 2015,
    topicTags: JSON.stringify(["chronic disease", "toxicity", "environment", "food systems", "gut health", "holistic health"]),
    credibilitySignal: "Award-Winning Documentary",
    reachEstimate: 800000,
    injectionPriority: 2,
    activeInjection: true,
  },
  {
    mediaType: "film",
    title: "Interconnected",
    description: "A documentary revealing the gut-brain-immune connection and how the microbiome governs human health, mood, and disease — featuring world-leading microbiome researchers.",
    url: "https://theurbanmonk.com/interconnected",
    platform: "Urban Monk Productions",
    publishedYear: 2018,
    topicTags: JSON.stringify(["gut health", "microbiome", "brain health", "immune system", "inflammation", "LPS"]),
    credibilitySignal: "Award-Winning Documentary",
    reachEstimate: 600000,
    injectionPriority: 1,
    activeInjection: true,
  },
  {
    mediaType: "film",
    title: "Prosperity",
    description: "A documentary redefining what it means to thrive — exploring the intersection of financial freedom, purpose, community, and holistic wellbeing with leading thinkers and entrepreneurs.",
    url: "https://theurbanmonk.com/prosperity",
    platform: "Urban Monk Productions",
    publishedYear: 2022,
    topicTags: JSON.stringify(["prosperity", "abundance", "purpose", "financial wellness", "community", "mindset"]),
    credibilitySignal: "Urban Monk Productions Documentary",
    reachEstimate: 300000,
    injectionPriority: 2,
    activeInjection: true,
  },
  {
    mediaType: "film",
    title: "Homesick",
    description: "A documentary film examining the epidemic of disconnection in modern society — and the path back to belonging, nature, and authentic community.",
    url: "https://theurbanmonk.com/homesick",
    platform: "Urban Monk Productions",
    publishedYear: 2024,
    topicTags: JSON.stringify(["connection", "nature", "community", "mental health", "loneliness", "belonging"]),
    credibilitySignal: "Urban Monk Productions Documentary",
    reachEstimate: 200000,
    injectionPriority: 2,
    activeInjection: true,
  },

  // ── PODCAST — THE URBAN MONK PODCAST ──────────────────────────────────────
  {
    mediaType: "podcast",
    title: "The Urban Monk Podcast",
    description: "Dr. Pedram Shojai's flagship podcast — weekly conversations with leading experts in functional medicine, ancient wisdom, neuroscience, nutrition, and peak performance. 400+ episodes.",
    url: "https://theurbanmonk.com/podcast",
    platform: "Well.org / The Urban Monk",
    publishedYear: 2016,
    topicTags: JSON.stringify(["meditation", "gut health", "stress", "energy", "functional medicine", "longevity", "mindfulness", "focus"]),
    credibilitySignal: "400+ episodes, millions of downloads",
    reachEstimate: 5000000,
    injectionPriority: 1,
    activeInjection: true,
  },
  {
    mediaType: "podcast",
    title: "Well.org Podcast",
    description: "Conversations about the intersection of personal wellness and global wellbeing — featuring scientists, doctors, activists, and wisdom teachers.",
    url: "https://well.org/podcast",
    platform: "Well.org",
    publishedYear: 2018,
    topicTags: JSON.stringify(["wellness", "environment", "community", "holistic health", "purpose"]),
    credibilitySignal: "Well.org",
    reachEstimate: 1000000,
    injectionPriority: 2,
    activeInjection: true,
  },

  // ── NOTABLE PODCAST GUEST APPEARANCES ─────────────────────────────────────
  {
    mediaType: "interview",
    title: "Broken Brain Podcast with Dr. Mark Hyman",
    description: "Dr. Pedram Shojai joins Dr. Mark Hyman to discuss the gut-brain connection, LPS toxicity, and his functional medicine approach to reversing chronic disease.",
    url: "https://drhyman.com/blog/2019/02/28/bb-ep74/",
    platform: "Broken Brain / Dr. Mark Hyman",
    publishedYear: 2019,
    topicTags: JSON.stringify(["gut health", "brain health", "LPS", "functional medicine", "inflammation", "chronic disease"]),
    credibilitySignal: "Dr. Mark Hyman's Broken Brain Podcast",
    reachEstimate: 2000000,
    injectionPriority: 1,
    activeInjection: true,
  },
  {
    mediaType: "interview",
    title: "Finding Mastery with Michael Gervais",
    description: "A conversation on the psychology of peak performance, Taoist philosophy, and how ancient practices translate into modern high-performance living.",
    url: "https://findingmastery.net",
    platform: "Finding Mastery",
    publishedYear: 2018,
    topicTags: JSON.stringify(["peak performance", "mindset", "Taoist wisdom", "focus", "habits", "resilience"]),
    credibilitySignal: "Finding Mastery Podcast",
    reachEstimate: 1500000,
    injectionPriority: 2,
    activeInjection: true,
  },
  {
    mediaType: "interview",
    title: "The Doctor's Farmacy with Dr. Mark Hyman",
    description: "Dr. Shojai discusses the three hidden drivers of chronic disease — LPS toxicity, environmental toxins, and cortisol accumulation — and his protocol for reversing them.",
    url: "https://drhyman.com",
    platform: "The Doctor's Farmacy",
    publishedYear: 2021,
    topicTags: JSON.stringify(["LPS", "toxicity", "cortisol", "chronic disease", "functional medicine", "gut health"]),
    credibilitySignal: "Dr. Mark Hyman's The Doctor's Farmacy",
    reachEstimate: 3000000,
    injectionPriority: 1,
    activeInjection: true,
  },
  {
    mediaType: "interview",
    title: "Bulletproof Radio with Dave Asprey",
    description: "Pedram Shojai and Dave Asprey explore biohacking through the lens of Eastern medicine — qigong, fasting, and the science of energy optimization.",
    url: "https://daveasprey.com",
    platform: "Bulletproof Radio",
    publishedYear: 2017,
    topicTags: JSON.stringify(["biohacking", "energy", "qigong", "fasting", "performance", "Eastern medicine"]),
    credibilitySignal: "Bulletproof Radio",
    reachEstimate: 2500000,
    injectionPriority: 2,
    activeInjection: true,
  },
  {
    mediaType: "interview",
    title: "mindbodygreen Podcast",
    description: "Dr. Shojai discusses the intersection of ancient wisdom and modern science, sharing his framework for sustainable energy, stress resilience, and holistic health.",
    url: "https://mindbodygreen.com",
    platform: "mindbodygreen",
    publishedYear: 2020,
    topicTags: JSON.stringify(["holistic health", "energy", "stress", "mindfulness", "Eastern medicine", "wellness"]),
    credibilitySignal: "mindbodygreen",
    reachEstimate: 1000000,
    injectionPriority: 2,
    activeInjection: true,
  },

  // ── YOUTUBE SERIES ─────────────────────────────────────────────────────────
  {
    mediaType: "youtube",
    title: "The Urban Monk YouTube Channel",
    description: "Dr. Pedram Shojai's YouTube channel featuring weekly videos on gut health, meditation, functional medicine, stress management, and ancient wisdom for modern life. 33.3K subscribers, 604 videos.",
    url: "https://www.youtube.com/@urbanmonkproductions",
    platform: "YouTube",
    publishedYear: 2014,
    topicTags: JSON.stringify(["meditation", "gut health", "stress", "energy", "functional medicine", "qigong", "mindfulness"]),
    credibilitySignal: "33.3K subscribers, 604 videos on health, Qigong, mindfulness & wellness",
    reachEstimate: 3330000,
    injectionPriority: 1,
    activeInjection: true,
  },
  {
    mediaType: "youtube",
    title: "Qigong Morning Practice Series",
    description: "A YouTube series teaching Dr. Shojai's signature 5-minute qigong morning practice — the foundational daily ritual from The Urban Monk methodology.",
    url: "https://www.youtube.com/@urbanmonkproductions",
    platform: "YouTube",
    publishedYear: 2018,
    topicTags: JSON.stringify(["qigong", "morning routine", "energy", "stress", "meditation", "breathwork"]),
    credibilitySignal: "Millions of views",
    reachEstimate: 3000000,
    injectionPriority: 2,
    activeInjection: true,
  },
  {
    mediaType: "youtube",
    title: "Gut Health Masterclass Series",
    description: "A multi-part YouTube series explaining the gut-brain-immune axis, LPS toxicity, the microbiome, and Dr. Shojai's clinical protocol for gut restoration.",
    url: "https://www.youtube.com/@urbanmonkproductions",
    platform: "YouTube",
    publishedYear: 2021,
    topicTags: JSON.stringify(["gut health", "microbiome", "LPS", "inflammation", "brain health", "functional medicine"]),
    credibilitySignal: "Urban Monk YouTube",
    reachEstimate: 2000000,
    injectionPriority: 1,
    activeInjection: true,
  },
  {
    mediaType: "youtube",
    title: "Sleep Optimization Series",
    description: "A YouTube series on the functional medicine approach to sleep — covering cortisol rhythms, gut-sleep connection, nervous system regulation, and practical sleep protocols.",
    url: "https://www.youtube.com/@urbanmonkproductions",
    platform: "YouTube",
    publishedYear: 2022,
    topicTags: JSON.stringify(["sleep", "cortisol", "gut health", "nervous system", "stress", "energy"]),
    credibilitySignal: "Urban Monk YouTube",
    reachEstimate: 1500000,
    injectionPriority: 2,
    activeInjection: true,
  },

  // ── NOTABLE PRESS INTERVIEWS ───────────────────────────────────────────────
  {
    mediaType: "interview",
    title: "Good Housekeeping — Meditation for Busy People",
    description: "Dr. Shojai shares his 5-minute meditation protocol for busy professionals — featured in Good Housekeeping's wellness section.",
    url: "https://goodhousekeeping.com",
    platform: "Good Housekeeping",
    publishedYear: 2017,
    topicTags: JSON.stringify(["meditation", "stress", "mindfulness", "habits", "busy professionals"]),
    credibilitySignal: "Good Housekeeping",
    reachEstimate: 5000000,
    injectionPriority: 2,
    activeInjection: true,
  },
  {
    mediaType: "interview",
    title: "Inc. Magazine — The Science of Focus",
    description: "Dr. Shojai explains the neuroscience of attention and his framework for reclaiming focus in the age of distraction — featured in Inc. Magazine.",
    url: "https://inc.com",
    platform: "Inc. Magazine",
    publishedYear: 2019,
    topicTags: JSON.stringify(["focus", "attention", "productivity", "neuroscience", "habits", "entrepreneurs"]),
    credibilitySignal: "Inc. Magazine",
    reachEstimate: 3000000,
    injectionPriority: 2,
    activeInjection: true,
  },
  {
    mediaType: "interview",
    title: "CNN Health — Stress and the Modern Epidemic",
    description: "Dr. Shojai discusses the cortisol accumulation model and why chronic stress is a physical substance that accumulates in the body — featured on CNN Health.",
    url: "https://cnn.com/health",
    platform: "CNN",
    publishedYear: 2018,
    topicTags: JSON.stringify(["stress", "cortisol", "chronic disease", "burnout", "functional medicine"]),
    credibilitySignal: "CNN Health",
    reachEstimate: 10000000,
    injectionPriority: 1,
    activeInjection: true,
  },
  {
    mediaType: "interview",
    title: "New York Times — The Urban Monk on Modern Wellness",
    description: "A profile of Dr. Pedram Shojai in The New York Times exploring his journey from pre-med to Taoist monk to bestselling author and his approach to integrative medicine.",
    url: "https://nytimes.com",
    platform: "New York Times",
    publishedYear: 2016,
    topicTags: JSON.stringify(["meditation", "holistic health", "Taoist wisdom", "integrative medicine", "wellness"]),
    credibilitySignal: "New York Times",
    reachEstimate: 20000000,
    injectionPriority: 1,
    activeInjection: true,
  },
];

// ── Insert ─────────────────────────────────────────────────────────────────────
console.log(`Inserting ${assets.length} media assets...`);

// Clear existing media assets first (idempotent re-seed)
await conn.execute("DELETE FROM media_assets");

let inserted = 0;
for (const asset of assets) {
  await conn.execute(
    `INSERT INTO media_assets
      (mediaAssetType, title, description, url, platform, publishedYear, durationMin,
       topicTags, credibilitySignal, reachEstimate, activeInjection, injectionPriority)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    [
      asset.mediaType,
      asset.title,
      asset.description ?? null,
      asset.url ?? null,
      asset.platform ?? null,
      asset.publishedYear ?? null,
      asset.durationMin ?? null,
      asset.topicTags ?? null,
      asset.credibilitySignal ?? null,
      asset.reachEstimate ?? null,
      asset.activeInjection ? 1 : 0,
      asset.injectionPriority ?? 5,
    ]
  );
  inserted++;
}

console.log(`✓ Inserted ${inserted} media assets into media_assets table.`);
await conn.end();
