-- ═══════════════════════════════════════════════════════════════════════════════
-- Script Factory v2.2 → v2.4 — PRODUCTION MIGRATION
--
-- Target : TiDB Serverless 8.0.11-TiDB-v8.5.3-serverless
--          gateway02.us-east-1.prod.aws.tidbcloud.com:4000
--          database iUgsiz76NwfDUVHZHV7CyJ
-- Source : branch feature/script-factory-v22 @ f330451
-- Author : written by hand from a live-schema diff. NOT generated by drizzle.
--
-- ┌─ READ THIS BEFORE EXECUTING ────────────────────────────────────────────┐
-- │ 1. DO NOT run `drizzle-kit migrate` or `drizzle-kit push` against this   │
-- │    database. The repo's migration history is UNREPLAYABLE: migration     │
-- │    0114 alters a column `vj_status` that no migration ever creates       │
-- │    (schema.ts calls it `status`), and seven files referenced by          │
-- │    drizzle/meta/_journal.json are absent. A clean replay dies partway.   │
-- │ 2. This file is ADDITIVE ONLY. No DROP, no RENAME, no MODIFY, no data    │
-- │    mutation. Every statement either creates something absent or adds a   │
-- │    nullable column.                                                     │
-- │ 3. Take the backup FIRST. See the plan document, Part 4.                 │
-- │ 4. Run section by section and read the verification output after each.   │
-- └─────────────────────────────────────────────────────────────────────────┘
--
-- WHAT THIS DOES NOT DO, DELIBERATELY
-- The naive live-vs-declared diff reports 55 "missing" columns. 35 of those are
-- the SAME column under two names — schema.ts says `ab_test_status`, production
-- has `status`; schema.ts says `yt_status`, production has `yt_pipeline_status`.
-- Adding them would leave production holding both the real column (with data)
-- and a new empty one that the app then reads and writes. No error is raised.
-- That is silent data divergence and it is NOT fixed here. Drift reconciliation
-- is a separate, deliberate piece of work; see the plan document, Part 6.
--
-- The reproducible evidence for the 16-vs-55 split:
--   node scripts/extract-schema-columns.mjs drizzle/schema.ts /tmp/cols.json
--   node scripts/pair-drift-vs-additions.mjs
--
-- CHARSET
-- Production is ALREADY utf8mb4 / utf8mb4_bin at server, database and column
-- level (verified: character_set_server=utf8mb4; every existing text column on
-- script_factory_outputs reports utf8mb4_bin). The utf8mb3 emoji-truncation risk
-- was a SANDBOX-only condition and does not exist here. New text columns below
-- still carry an explicit CHARACTER SET utf8mb4 so they cannot inherit a
-- different default if one is ever changed.
--
-- BLAST RADIUS (live row counts at time of writing)
--   script_factory_outputs           5 rows   (all status='draft')
--   analog_data_entries              1 row
--   collective_sourcing_candidates   0 rows
-- TiDB performs schema changes online and non-blocking, and these are tiny
-- tables. Expect sub-second per statement. No downtime window is required for
-- the DDL itself.
-- ═══════════════════════════════════════════════════════════════════════════════


-- ───────────────────────────────────────────────────────────────────────────────
-- SECTION 0 — PRE-FLIGHT. Run this alone. Do not proceed unless it matches.
-- ───────────────────────────────────────────────────────────────────────────────

-- 0.1 Confirm you are pointed at the intended database and engine.
SELECT
  DATABASE()                AS current_db,
  VERSION()                 AS server_version,
  @@character_set_server    AS cs_server,
  @@collation_server        AS coll_server;
-- EXPECT: current_db = iUgsiz76NwfDUVHZHV7CyJ
--         server_version contains "TiDB"
--         cs_server = utf8mb4

-- 0.2 Confirm the three tables to be created are genuinely absent.
--     If ANY row comes back, STOP: something already created them and this
--     file's assumptions no longer hold.
SELECT table_name
FROM information_schema.tables
WHERE table_schema = DATABASE()
  AND table_name IN ('research_jobs', 'suggested_ideas', 'topic_nodes');
-- EXPECT: empty result set.

-- 0.3 Confirm script_factory_outputs is still at the pre-v2.2 shape (15 columns)
--     and none of the 14 columns we add already exist.
--
--     This IN-list MUST stay in lockstep with the ADD COLUMN list in Section 2.
--     If they diverge, this check silently stops guarding whichever column was
--     omitted — it would return 0 and read as "safe" while that column already
--     existed. `scripts/verify-column-names.mjs` asserts set-equality between
--     Section 2 and drizzle/schema.ts, but it does NOT read this list, so keep
--     them aligned by hand. (metric_version was missing here in the first draft.)
SELECT COUNT(*) AS existing_v22_plus_columns
FROM information_schema.columns
WHERE table_schema = DATABASE()
  AND table_name = 'script_factory_outputs'
  AND column_name IN (
    'persona_id','analog_data_entry_ids','target_length_minutes','source_idea_id',
    'research_job_id','word_count','production_script_id','pattern_composition',
    'parent_script_id','variant_label','variant_of_root_id','generation_params',
    'section_history','metric_version'
  );
-- EXPECT: 0

-- 0.4 Record the row counts you are about to migrate, for the rollback record.
SELECT 'script_factory_outputs' AS tbl, COUNT(*) AS rows_before FROM script_factory_outputs
UNION ALL SELECT 'analog_data_entries',            COUNT(*) FROM analog_data_entries
UNION ALL SELECT 'collective_sourcing_candidates', COUNT(*) FROM collective_sourcing_candidates;
-- EXPECT at time of writing: 5 / 1 / 0. Note the actual values before continuing.


-- ───────────────────────────────────────────────────────────────────────────────
-- SECTION 1 — NEW TABLES (3)
--
-- Column names, types, enum members and nullability are taken from
-- drizzle/schema.ts, which is the authority for what the running code reads and
-- writes. They are NOT copied from drizzle/0124 and 0125, because those files
-- have drifted from the code in three ways that matter:
--
--   (a) 0124 declares recommended_patterns / vidiq_data / outlier_videos as
--       JSON. Current schema.ts declares them via longtextJson(), whose
--       dataType() returns "longtext" (drizzle/longtextJson.ts:42). This was a
--       deliberate later correction — the file's own header calls it
--       "FINDING #10 STRUCTURAL FIX". A JSON column validates and rejects
--       malformed input; longtext accepts it and the app parses. Creating JSON
--       columns the code treats as longtext would typecheck and then misbehave
--       at the database boundary. Every such column below is LONGTEXT and
--       annotated.
--   (b) 0124's suggested_ideas.idea_source enum has 2 members; schema.ts has 3
--       ('manual' was added later). The 3-member version is used.
--   (c) schema.ts carries columns 0124/0125 never create:
--       research_jobs.structure_summary, topic_nodes.topic_status,
--       topic_nodes.last_mined_at, suggested_ideas.topic_node_id.
--
-- Index definitions ARE taken from 0124/0125, since those were written with the
-- query patterns in mind and are not contradicted by schema.ts.
-- ───────────────────────────────────────────────────────────────────────────────

-- 1.1 research_jobs — deep-research pipeline job records.
CREATE TABLE IF NOT EXISTS `research_jobs` (
  `id`                   INT NOT NULL AUTO_INCREMENT,
  `topic`                VARCHAR(500) CHARACTER SET utf8mb4 NOT NULL,
  `seed_keyword`         VARCHAR(255) CHARACTER SET utf8mb4 NULL,
  `research_status`      ENUM('pending','researching_outliers','fetching_transcripts','extracting_patterns','complete','failed') NOT NULL DEFAULT 'pending',
  `outlier_videos`       LONGTEXT CHARACTER SET utf8mb4 NULL,   -- JSON-in-longtext; was JSON in 0124
  `transcript_video_ids` LONGTEXT CHARACTER SET utf8mb4 NULL,   -- JSON-in-longtext; was JSON in 0124
  `pattern_ids`          LONGTEXT CHARACTER SET utf8mb4 NULL,   -- JSON-in-longtext; was JSON in 0124
  `transcripts_fetched`  INT NOT NULL DEFAULT 0,
  `transcripts_cached`   INT NOT NULL DEFAULT 0,
  `transcripts_failed`   INT NOT NULL DEFAULT 0,
  `quota_blocked`        BOOLEAN NOT NULL DEFAULT FALSE,
  `notes`                TEXT CHARACTER SET utf8mb4 NULL,
  `structure_summary`    LONGTEXT CHARACTER SET utf8mb4 NULL,   -- absent from 0124; present in schema.ts
  `error_message`        VARCHAR(512) CHARACTER SET utf8mb4 NULL,
  `created_at`           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `research_jobs_id` PRIMARY KEY (`id`)
) CHARACTER SET utf8mb4;

CREATE INDEX `research_jobs_topic_idx`  ON `research_jobs` (`topic`);
CREATE INDEX `research_jobs_status_idx` ON `research_jobs` (`research_status`);

-- 1.2 suggested_ideas — persistent idea engine.
CREATE TABLE IF NOT EXISTS `suggested_ideas` (
  `id`                    INT NOT NULL AUTO_INCREMENT,
  `batch_id`              VARCHAR(32) CHARACTER SET utf8mb4 NOT NULL,
  `week_label`            VARCHAR(16) CHARACTER SET utf8mb4 NOT NULL,
  `idea_source`           ENUM('weekly_auto','manual_generate','manual') NOT NULL DEFAULT 'manual_generate',
  `topic`                 VARCHAR(500) CHARACTER SET utf8mb4 NOT NULL,
  `rationale`             TEXT CHARACTER SET utf8mb4 NULL,
  `audience_alignment`    INT NULL,
  `content_gap`           TEXT CHARACTER SET utf8mb4 NULL,
  `recommended_format`    VARCHAR(64) CHARACTER SET utf8mb4 NULL,
  `recommended_patterns`  LONGTEXT CHARACTER SET utf8mb4 NULL,  -- JSON-in-longtext; was JSON in 0124
  `analog_data_source`    TEXT CHARACTER SET utf8mb4 NULL,
  `analog_data_entry_id`  INT NULL,
  `persona_id`            INT NULL,
  `vidiq_data`            LONGTEXT CHARACTER SET utf8mb4 NULL,  -- JSON-in-longtext; was JSON in 0124
  `seed_keyword`          VARCHAR(255) CHARACTER SET utf8mb4 NULL,
  `idea_status`           ENUM('suggested','shortlisted','dismissed','generated') NOT NULL DEFAULT 'suggested',
  `generated_script_id`   INT NULL,
  `topic_node_id`         INT NULL,                             -- absent from 0124; present in schema.ts
  `created_at`            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `suggested_ideas_id` PRIMARY KEY (`id`)
) CHARACTER SET utf8mb4;

CREATE INDEX `suggested_ideas_week_idx`    ON `suggested_ideas` (`week_label`);
CREATE INDEX `suggested_ideas_batch_idx`   ON `suggested_ideas` (`batch_id`);
CREATE INDEX `suggested_ideas_status_idx`  ON `suggested_ideas` (`idea_status`);
CREATE INDEX `suggested_ideas_created_idx` ON `suggested_ideas` (`created_at`);

-- 1.3 topic_nodes — topic tree for idea expansion.
CREATE TABLE IF NOT EXISTS `topic_nodes` (
  `id`                   INT NOT NULL AUTO_INCREMENT,
  `parent_id`            INT NULL,
  `path`                 VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `depth`                INT NOT NULL DEFAULT 0,
  `label`                VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL,
  `description`          TEXT CHARACTER SET utf8mb4 NULL,
  `topic_source_type`    ENUM('analog_extraction','llm_expansion','manual') NOT NULL DEFAULT 'manual',
  `analog_data_entry_id` INT NULL,
  `persona_id`           INT NULL,
  `vidiq_data`           LONGTEXT CHARACTER SET utf8mb4 NULL,   -- JSON-in-longtext; was JSON in 0125
  `topic_status`         ENUM('active','archived') NOT NULL DEFAULT 'active',  -- absent from 0125
  `last_mined_at`        DATETIME NULL,                          -- absent from 0125
  `created_at`           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `topic_nodes_id` PRIMARY KEY (`id`)
) CHARACTER SET utf8mb4;

CREATE INDEX `topic_nodes_parent_idx` ON `topic_nodes` (`parent_id`);
CREATE INDEX `topic_nodes_path_idx`   ON `topic_nodes` (`path`);
CREATE INDEX `topic_nodes_status_idx` ON `topic_nodes` (`topic_status`);


-- ───────────────────────────────────────────────────────────────────────────────
-- SECTION 2 — script_factory_outputs: 14 NEW COLUMNS
--
-- Every one is nullable with no default, so the 5 existing rows are untouched
-- and read back as NULL. No existing column is modified. The app treats NULL on
-- all of these as "not recorded", which is exactly what the 5 legacy rows are.
--
-- NOTE ON generation_params AND THE REGENERATE UI: rows with NULL
-- generation_params cannot be regenerated as variants, because the frozen
-- parameters that a variant replays do not exist for them. The workspace
-- correctly disables the Regenerate group for such rows and shows
-- "Unavailable for this script". After this migration all 5 legacy rows will be
-- in that state. That is honest behaviour, not a bug — see plan document Part 5.
-- ───────────────────────────────────────────────────────────────────────────────

ALTER TABLE `script_factory_outputs`
  -- v2.2: research-first generation inputs
  ADD COLUMN `persona_id`            INT NULL,
  ADD COLUMN `analog_data_entry_ids` LONGTEXT CHARACTER SET utf8mb4 NULL,  -- JSON-in-longtext
  ADD COLUMN `target_length_minutes` INT NULL,
  ADD COLUMN `source_idea_id`        INT NULL,
  ADD COLUMN `research_job_id`       INT NULL,
  ADD COLUMN `word_count`            INT NULL,
  ADD COLUMN `production_script_id`  INT NULL,
  ADD COLUMN `pattern_composition`   LONGTEXT CHARACTER SET utf8mb4 NULL,  -- JSON-in-longtext
  -- v2.3: variant lineage
  ADD COLUMN `parent_script_id`      INT NULL,
  ADD COLUMN `variant_label`         VARCHAR(120) CHARACTER SET utf8mb4 NULL,
  ADD COLUMN `variant_of_root_id`    INT NULL,
  ADD COLUMN `generation_params`     LONGTEXT CHARACTER SET utf8mb4 NULL,  -- JSON-in-longtext; carries ctaStyle from v2.4
  ADD COLUMN `section_history`       LONGTEXT CHARACTER SET utf8mb4 NULL,  -- JSON-in-longtext; per-section undo
  -- v2.4: which DEFINITION produced verification_pct on this row.
  --
  -- verification_pct has held two incompatible measures under one name. Pre-v2.2
  -- it was the share of all bracketed markers that happened to be [VERIFIED] — a
  -- number that moved when a script was labelled more thoroughly, even though its
  -- grounding had not changed. From v2.2 it is the share of SECTIONS containing
  -- grounded material. scriptMetrics.ts already computed the version string and
  -- then discarded it, so a row could not say which definition produced its number.
  --
  -- NULLABLE ON PURPOSE, AND THAT IS THE POINT: the 5 rows already in production
  -- were written under the OLD definition and will read NULL, which is the truthful
  -- value. Backfilling them with 'v2.2-instance' would relabel a marker-ratio
  -- number as a section-ratio number and make this column lie about exactly the
  -- rows it exists to disambiguate. Read NULL as "pre-v2.2, not comparable".
  ADD COLUMN `metric_version`        VARCHAR(16) CHARACTER SET utf8mb4 NULL;

-- Variant lookups. Originals store NULL in variant_of_root_id (never their own
-- id), so the family key is COALESCE(variant_of_root_id, id) and a bare
-- `WHERE variant_of_root_id = N` would omit the root from its own family.
-- These indexes serve the two query shapes the code actually issues:
-- "top-level rows only" (parent_script_id IS NULL) and "members of family N".
CREATE INDEX `sfo_parent_idx`       ON `script_factory_outputs` (`parent_script_id`);
CREATE INDEX `sfo_variant_root_idx` ON `script_factory_outputs` (`variant_of_root_id`);


-- ───────────────────────────────────────────────────────────────────────────────
-- SECTION 3 — analog_data_entries: offer_profile
--
-- This is the column that binds a script to a real offer. Without it every
-- generation runs with a null offer profile, which the v2.4 sell-density lint
-- reports as not_applicable rather than passed. 1 live row, untouched.
-- ───────────────────────────────────────────────────────────────────────────────

ALTER TABLE `analog_data_entries`
  ADD COLUMN `offer_profile` TEXT CHARACTER SET utf8mb4 NULL;


-- ───────────────────────────────────────────────────────────────────────────────
-- SECTION 4 — collective_sourcing_candidates  ⟨INTENTIONALLY EXCLUDED — DO NOT RUN⟩
--
-- EXCLUDED BY OWNER DECISION (review round 1, Q3: "defer, note it as a v2.5
-- micro-migration"). The statement is retained below, COMMENTED OUT, so the
-- analysis is not lost and the v2.5 migration can lift it verbatim. Running it
-- is not part of this deployment.
--
-- WHY IT WAS DEFERRED: this table has STRUCTURALLY DIVERGED from its declaration,
-- not merely drifted in naming, and nothing in v2.2–v2.4 reads or writes it. There
-- is no reason to touch a diverged table during a Script Factory deploy.
--
-- THE ANALYSIS, PRESERVED FOR v2.5
-- --------------------------------
-- schema.ts expects created_at / updated_at / status / notes;
-- in naming. schema.ts expects created_at / updated_at / status / notes;
-- production has csc_createdAt / csc_status / imported_at / reviewed_at /
-- collective_product_handle. The pairing analysis matched created_at→csc_createdAt
-- and status→csc_status as drift (no DDL), leaving `notes` and `updated_at`
-- genuinely absent.
--
-- INCONSISTENCY TO BE AWARE OF: schema.ts declares this table's updated_at as
--   bigint("updated_at", { mode: "number" }).notNull().$defaultFn(() => Date.now())
-- i.e. epoch MILLISECONDS as BIGINT, whereas script_factory_outputs.updated_at is
-- DATETIME DEFAULT CURRENT_TIMESTAMP. Two conventions for the same column name in
-- the same database. The BIGINT form below matches THIS table's own declaration,
-- which is what the code writing to this table expects.
--
-- The declaration is .notNull() with an app-side default. Adding a NOT NULL
-- column requires a value for existing rows — there are 0 rows here, so it is
-- safe today. It is written NOT NULL DEFAULT 0 anyway so that the statement
-- remains valid if rows appear between now and execution; the app always writes
-- an explicit Date.now(), so a stored 0 would only ever be a visible marker of a
-- row inserted outside the app.
-- ───────────────────────────────────────────────────────────────────────────────

-- DEFERRED TO v2.5 — deliberately commented out, not deleted:
-- ALTER TABLE `collective_sourcing_candidates`
--   ADD COLUMN `notes`      TEXT CHARACTER SET utf8mb4 NULL,
--   ADD COLUMN `updated_at` BIGINT NOT NULL DEFAULT 0;


-- ───────────────────────────────────────────────────────────────────────────────
-- SECTION 5 — POST-MIGRATION VERIFICATION. Run every query. Check every EXPECT.
-- ───────────────────────────────────────────────────────────────────────────────

-- 5.1 All three tables now exist.
SELECT table_name, table_collation
FROM information_schema.tables
WHERE table_schema = DATABASE()
  AND table_name IN ('research_jobs','suggested_ideas','topic_nodes')
ORDER BY table_name;
-- EXPECT: 3 rows. research_jobs, suggested_ideas, topic_nodes. collation utf8mb4_*.

-- 5.2 Their column counts match the declaration.
SELECT table_name, COUNT(*) AS column_count
FROM information_schema.columns
WHERE table_schema = DATABASE()
  AND table_name IN ('research_jobs','suggested_ideas','topic_nodes')
GROUP BY table_name ORDER BY table_name;
-- EXPECT: research_jobs 16, suggested_ideas 20, topic_nodes 14.

-- 5.3 All 14 script_factory_outputs columns landed, with the right types.
SELECT column_name, column_type, is_nullable, character_set_name
FROM information_schema.columns
WHERE table_schema = DATABASE()
  AND table_name = 'script_factory_outputs'
  AND column_name IN (
    'persona_id','analog_data_entry_ids','target_length_minutes','source_idea_id',
    'research_job_id','word_count','production_script_id','pattern_composition',
    'parent_script_id','variant_label','variant_of_root_id','generation_params',
    'section_history','metric_version'
  )
ORDER BY column_name;
-- EXPECT: 14 rows. Every is_nullable = YES. The four *_ids/params/history/
--         composition columns are longtext with character_set utf8mb4.
--         variant_label is varchar(120), metric_version varchar(16). The rest int.
--         EVERY character_set_name that is non-NULL must read utf8mb4. A latin1
--         here means the ALTER did not inherit the table charset — STOP, because
--         emoji and en-dashes would be silently mangled on write.

-- 5.4 The 5 pre-existing rows are intact and their new columns read NULL.
SELECT COUNT(*) AS total_rows,
       SUM(CASE WHEN generation_params IS NULL THEN 1 ELSE 0 END) AS null_gen_params,
       SUM(CASE WHEN parent_script_id  IS NULL THEN 1 ELSE 0 END) AS null_parent,
       SUM(CASE WHEN metric_version    IS NULL THEN 1 ELSE 0 END) AS null_metric_version,
       SUM(CASE WHEN script_body IS NULL OR script_body = '' THEN 1 ELSE 0 END) AS empty_bodies
FROM script_factory_outputs;
-- EXPECT: total_rows unchanged from pre-flight 0.4 (5 at time of writing).
--         null_gen_params = total_rows. null_parent = total_rows.
--         null_metric_version = total_rows. These 5 rows were written under the
--         PRE-v2.2 metric definition, so NULL is the truthful value and a
--         non-NULL here would mean something backfilled a label it cannot know.
--         empty_bodies = 0  ← if this is non-zero, existing data was damaged. STOP.

-- 5.5 offer_profile exists and the 1 existing row is untouched.
SELECT COUNT(*) AS rows_total,
       SUM(CASE WHEN offer_profile IS NULL THEN 1 ELSE 0 END) AS null_offer_profile
FROM analog_data_entries;
-- EXPECT: rows_total unchanged from pre-flight (1). null_offer_profile = rows_total.

-- 5.6 Indexes were created.
SELECT table_name, index_name
FROM information_schema.statistics
WHERE table_schema = DATABASE()
  AND index_name IN (
    'sfo_parent_idx','sfo_variant_root_idx',
    'research_jobs_topic_idx','research_jobs_status_idx',
    'suggested_ideas_week_idx','suggested_ideas_batch_idx',
    'suggested_ideas_status_idx','suggested_ideas_created_idx',
    'topic_nodes_parent_idx','topic_nodes_path_idx','topic_nodes_status_idx'
  )
GROUP BY table_name, index_name ORDER BY table_name, index_name;
-- EXPECT: 11 rows.

-- 5.7 Charset assertion across every new text column. READ-ONLY.
--
-- REPLACES A DEFECTIVE WRITE PROBE. The first draft of this step inserted a row
-- containing emoji into analog_data_entries and deleted it again. Two things were
-- wrong with that. First, it would have FAILED on a completely healthy migration:
-- analog_data_entries.content is NOT NULL with no default, so an INSERT supplying
-- only offer_profile errors — and an error at the final verification step reads as
-- "the migration broke something" when nothing broke. Second, it wrote junk into a
-- real business table (this is where the sales page lives) to test a property that
-- information_schema reports directly.
--
-- This version asserts the same property by reading the catalogue, so the whole
-- migration file now performs NO data mutation of any kind — only DDL and SELECTs.
SELECT table_name, column_name, character_set_name, collation_name
FROM information_schema.columns
WHERE table_schema = DATABASE()
  AND (
        (table_name = 'script_factory_outputs' AND column_name IN
          ('analog_data_entry_ids','pattern_composition','variant_label',
           'generation_params','section_history','metric_version'))
     OR (table_name = 'analog_data_entries'    AND column_name = 'offer_profile')
     OR (table_name IN ('research_jobs','suggested_ideas','topic_nodes')
           AND character_set_name IS NOT NULL)
      )
ORDER BY table_name, column_name;
-- EXPECT: every row reads character_set_name = utf8mb4 (collation utf8mb4_bin on
--         this server). Any latin1 or utf8mb3 row means that column cannot store
--         4-byte characters and emoji/en-dashes will be mangled on write. STOP and
--         fix that column before deploying the application code.
--
-- Production was confirmed utf8mb4 at server, database and existing-column level
-- during planning, so this is a regression check rather than a discovery.

-- 5.8 Nothing was dropped: total table count should have gone UP by exactly 3.
SELECT COUNT(*) AS table_count FROM information_schema.tables WHERE table_schema = DATABASE();
-- EXPECT: 149 (was 146 before this migration).

-- 5.9 No data was written by this file. Confirm the row counts are unchanged.
SELECT
  (SELECT COUNT(*) FROM script_factory_outputs) AS sfo_rows,
  (SELECT COUNT(*) FROM analog_data_entries)    AS ade_rows,
  (SELECT COUNT(*) FROM research_jobs)          AS rj_rows,
  (SELECT COUNT(*) FROM suggested_ideas)        AS si_rows,
  (SELECT COUNT(*) FROM topic_nodes)            AS tn_rows;
-- EXPECT: sfo_rows and ade_rows identical to pre-flight 0.4. The three new tables
--         read 0 — they were created empty and this file inserts nothing.

-- ═══════════════════════════════════════════════════════════════════════════════
-- END. If any EXPECT failed, stop and consult v24-production-rollback.sql.
-- ═══════════════════════════════════════════════════════════════════════════════
